In [118]:
import pandas as pd
import numpy as np

In [119]:
df=pd.read_csv("C:/Users/chanc/OneDrive/Desktop/historical_data.csv")

In [120]:
print(df)

                                           Account      Coin  Execution Price  \
0       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9769
1       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9800
2       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9855
3       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9874
4       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9894
...                                            ...       ...              ...
211219  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211220  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211221  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211222  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211223  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010

        Size Tokens  Size USD  Side     Timestamp IST  Start Position  \
0            986.87   7872.16   BUY   2/12/2024 22:50        0.000000
1             16.00    127.68   BUY   2/12/2024 22:50      986.524596
2            144.09   1150.63   BUY   2/12/2024 22:50     1002.518996
3            142.98   1142.04   BUY   2/12/2024 22:50     1146.558564
4              8.73     69.75   BUY   2/12/2024 22:50     1289.488521
...             ...       ...   ...               ...             ...
211219       382.20    420.80  SELL  25-04-2025 15:35     7546.600000
211220      2124.10   2338.63  SELL  25-04-2025 15:35     7164.400000
211221       423.40    466.16  SELL  25-04-2025 15:35     5040.300000
211222      3599.80   3963.38  SELL  25-04-2025 15:35     4616.900000
211223      1017.10   1119.83  SELL  25-04-2025 15:35     1017.100000

         Direction  Closed PnL  \
0              Buy      0.0000
1              Buy      0.0000
2              Buy      0.0000
3              Buy      0.0000
4              Buy      0.0000
...            ...         ...
211219  Close Long    -20.2566
211220  Close Long   -112.5773
211221  Close Long    -22.4402
211222  Close Long   -190.7894
211223  Close Long    -53.9063

                                         Transaction Hash     Order ID  \
0       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
1       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
2       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
3       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
4       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
...                                                   ...          ...
211219  0xcd339c08dc7b615a993c0422374d8e02027400092bc2...  88803313862
211220  0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...  88803313862
211221  0x0780085b0c0a943eea800422374d920204c100edf579...  88803313862
211222  0x349c29934913b25c89e20422374d920204cd008b8a0e...  88803313862
211223  0xac77fab973c455d77a670422374d9602039800f1f78c...  88803313862

        Crossed       Fee      Trade ID     Timestamp
0          True  0.345404  8.950000e+14  1.730000e+12
1          True  0.005600  4.430000e+14  1.730000e+12
2          True  0.050431  6.600000e+14  1.730000e+12
3          True  0.050043  1.080000e+15  1.730000e+12
4          True  0.003055  1.050000e+15  1.730000e+12
...         ...       ...           ...           ...
211219    False  0.042080  1.990000e+14  1.750000e+12
211220    False  0.233863  9.260000e+14  1.750000e+12
211221    False  0.046616  6.930000e+14  1.750000e+12
211222    False  0.396337  4.180000e+14  1.750000e+12
211223    False  0.111982  3.270000e+14  1.750000e+12

[211224 rows x 16 columns]

In [121]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  str
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), str(6)
memory usage: 24.4 MB
None

In [122]:
print(df.duplicated().sum())

0

In [123]:
print(df.isnull().sum())

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [124]:
print(df['Timestamp IST'])

0          2/12/2024 22:50
1          2/12/2024 22:50
2          2/12/2024 22:50
3          2/12/2024 22:50
4          2/12/2024 22:50
                ...
211219    25-04-2025 15:35
211220    25-04-2025 15:35
211221    25-04-2025 15:35
211222    25-04-2025 15:35
211223    25-04-2025 15:35
Name: Timestamp IST, Length: 211224, dtype: str

In [125]:
df['Timestamp IST']=pd.to_datetime(df['Timestamp IST'],dayfirst=True,errors='coerce')

In [126]:
df['Timestamp IST'].head(10)

0   2024-12-02 22:50:00
1   2024-12-02 22:50:00
2   2024-12-02 22:50:00
3   2024-12-02 22:50:00
4   2024-12-02 22:50:00
5   2024-12-02 22:50:00
6   2024-12-02 22:50:00
7   2024-12-02 22:50:00
8   2024-12-02 22:50:00
9   2024-12-02 22:50:00
Name: Timestamp IST, dtype: datetime64[us]

In [127]:
df[df['Timestamp IST'].isna()]

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
224,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,DYDX,0.63005,28.7,18.08,BUY,NaT,350000.0,Open Long,0.0000,0x7b46ccfbc6de6d29ed63041fc7608b01bc00943d76ed...,80499480660,True,0.006074,8.210000e+14,1.740000e+12
225,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,DYDX,0.63007,3072.9,1936.14,BUY,NaT,350028.7,Open Long,0.0000,0x7b46ccfbc6de6d29ed63041fc7608b01bc00943d76ed...,80499480660,True,0.650543,6.870000e+13,1.740000e+12
226,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,DYDX,0.63007,2724.5,1716.63,BUY,NaT,353101.6,Open Long,0.0000,0x7b46ccfbc6de6d29ed63041fc7608b01bc00943d76ed...,80499480660,True,0.576786,3.790000e+14,1.740000e+12
227,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,DYDX,0.63029,1568.6,988.67,BUY,NaT,355826.1,Open Long,0.0000,0x7b46ccfbc6de6d29ed63041fc7608b01bc00943d76ed...,80499480660,True,0.332193,4.410000e+14,1.740000e+12
228,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,DYDX,0.63046,1473.6,929.05,BUY,NaT,357394.7,Open Long,0.0000,0x7b46ccfbc6de6d29ed63041fc7608b01bc00943d76ed...,80499480660,True,0.312159,9.660000e+14,1.740000e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.10100,382.2,420.80,SELL,NaT,7546.6,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,88803313862,False,0.042080,1.990000e+14,1.750000e+12
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.10100,2124.1,2338.63,SELL,NaT,7164.4,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,88803313862,False,0.233863,9.260000e+14,1.750000e+12
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.10100,423.4,466.16,SELL,NaT,5040.3,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,88803313862,False,0.046616,6.930000e+14,1.750000e+12
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.10100,3599.8,3963.38,SELL,NaT,4616.9,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,88803313862,False,0.396337,4.180000e+14,1.750000e+12
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.10100,1017.1,1119.83,SELL,NaT,1017.1,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,88803313862,False,0.111982,3.270000e+14,1.750000e+12

In [128]:
df = df.dropna(subset=['Timestamp IST'])

In [129]:
df.isnull().sum()

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [130]:
df=df.reset_index(drop=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 79225 entries, 0 to 79224
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Account           79225 non-null  str
 1   Coin              79225 non-null  str
 2   Execution Price   79225 non-null  float64
 3   Size Tokens       79225 non-null  float64
 4   Size USD          79225 non-null  float64
 5   Side              79225 non-null  str
 6   Timestamp IST     79225 non-null  datetime64[us]
 7   Start Position    79225 non-null  float64
 8   Direction         79225 non-null  str
 9   Closed PnL        79225 non-null  float64
 10  Transaction Hash  79225 non-null  str
 11  Order ID          79225 non-null  int64
 12  Crossed           79225 non-null  bool
 13  Fee               79225 non-null  float64
 14  Trade ID          79225 non-null  float64
 15  Timestamp         79225 non-null  float64
dtypes: bool(1), datetime64[us](1), float64(8), int64(1), str(5)
memory usage: 9.1 MB

In [131]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms', utc=True).dt.tz_convert('Asia/Kolkata')
df = df.dropna(subset=['Timestamp'])
df = df.reset_index(drop=True)

df['Date'] = df['Timestamp'].dt.date

In [132]:
df[['Timestamp', 'Date']].head()

                  Timestamp        Date
0 2024-10-27 09:03:20+05:30  2024-10-27
1 2024-10-27 09:03:20+05:30  2024-10-27
2 2024-10-27 09:03:20+05:30  2024-10-27
3 2024-10-27 09:03:20+05:30  2024-10-27
4 2024-10-27 09:03:20+05:30  2024-10-27

In [133]:
daily_pnl_trader = df.groupby(['Date', 'Account'])['Closed PnL'].sum().reset_index()
daily_pnl_trader

          Date                                     Account     Closed PnL
0   2023-03-28  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891       0.000000
1   2023-11-15  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891       0.000000
2   2023-11-15  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23   -1860.503628
3   2024-03-09  0x4f93fead39b70a1824f981a54d4e55b278e9f760   16482.483389
4   2024-03-09  0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4  106364.967649
..         ...                                         ...            ...
75  2025-06-15  0xa0feb3725a9335f49874d7cd8eaad6be45b27416    1449.529436
76  2025-06-15  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  102460.171640
77  2025-06-15  0xbaaaf6571ab7d571043ff1e313a9609a10637864       1.860320
78  2025-06-15  0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3 -113601.020138
79  2025-06-15  0xbee1707d6b44d4d52bfe19e41f8a828645437aab    1364.022527

[80 rows x 3 columns]

In [134]:
daily_pnl_trader=daily_pnl_trader[daily_pnl_trader['Closed PnL']>0]

In [135]:
daily_pnl_trader

          Date                                     Account    Closed PnL
3   2024-03-09  0x4f93fead39b70a1824f981a54d4e55b278e9f760  1.648248e+04
4   2024-03-09  0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4  1.063650e+05
6   2024-07-03  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891  2.157548e+02
9   2024-07-03  0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4  1.565760e+00
12  2024-07-03  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  1.257785e+04
14  2024-10-27  0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd  6.032818e+03
15  2024-10-27  0x271b280974205ca63b716753467d5a371de622ab  2.088175e+02
16  2024-10-27  0x28736f43f1e871e6aa8b1148d38d4994275d72c4  4.477347e+04
17  2024-10-27  0x2c229d22b100a7beb69122eed721cee9b24011dd  4.145663e+04
18  2024-10-27  0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891  1.356693e+01
19  2024-10-27  0x39cef799f8b69da1995852eea189df24eb5cae3c  4.205008e+03
20  2024-10-27  0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6  1.536977e+03
21  2024-10-27  0x420ab45e0bd8863569a5efbb9c05d91f40624641  1.762460e+03
23  2024-10-27  0x47add9a56df66b524d5e2c1993a43cde53b6ed85  9.613382e+03
24  2024-10-27  0x4f93fead39b70a1824f981a54d4e55b278e9f760  5.452990e+04
26  2024-10-27  0x6d6a4b953f202f8df5bed40692e7fd865318264a  1.060851e+03
28  2024-10-27  0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4  5.525336e+03
29  2024-10-27  0x8381e6d82f1affd39a336e143e081ef7620a3b7f  1.171768e+01
30  2024-10-27  0x8477e447846c758f5a675856001ea72298fd9cb5  8.266137e+03
31  2024-10-27  0xa520ded057a32086c40e7dd6ed4eb8efb82c00e0  4.135773e+04
32  2024-10-27  0xae5eacaf9c6b9111fd53034a602c192a04e082ed  2.092551e+04
33  2024-10-27  0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb  5.501524e+01
34  2024-10-27  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  1.199286e+06
36  2024-10-27  0xbee1707d6b44d4d52bfe19e41f8a828645437aab  1.996946e+05
37  2025-02-20  0x083384f897ee0f19899168e3b1bec365f52a9012  1.535039e+06
39  2025-02-20  0x271b280974205ca63b716753467d5a371de622ab  2.997093e+04
41  2025-02-20  0x2c229d22b100a7beb69122eed721cee9b24011dd  3.486709e+04
44  2025-02-20  0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6  7.966494e+03
45  2025-02-20  0x420ab45e0bd8863569a5efbb9c05d91f40624641  3.007613e+04
46  2025-02-20  0x430f09841d65beb3f27765503d0f850b8bce7713  2.841086e+04
48  2025-02-20  0x4acb90e786d897ecffb614dc822eb231b4ffb9f4  4.048552e+05
49  2025-02-20  0x4f93fead39b70a1824f981a54d4e55b278e9f760  9.806789e+04
50  2025-02-20  0x513b8629fe877bb581bf244e326a047b249c4ff1  3.993830e+04
51  2025-02-20  0x6d6a4b953f202f8df5bed40692e7fd865318264a  3.775177e+03
52  2025-02-20  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  1.560309e+05
53  2025-02-20  0x72c6a4624e1dffa724e6d00d64ceae698af892a0  2.017160e+05
54  2025-02-20  0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4  5.744476e+04
55  2025-02-20  0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f  1.000353e+04
56  2025-02-20  0x8170715b3b381dffb7062c0298972d4727a0a63b  5.238479e+04
57  2025-02-20  0x8381e6d82f1affd39a336e143e081ef7620a3b7f  1.058935e+04
58  2025-02-20  0x8477e447846c758f5a675856001ea72298fd9cb5  1.775469e+04
59  2025-02-20  0x92f17e8d81a944691c10e753af1b1baae1a2cd0d  1.567187e+04
60  2025-02-20  0xa0feb3725a9335f49874d7cd8eaad6be45b27416  1.382245e+04
62  2025-02-20  0xae5eacaf9c6b9111fd53034a602c192a04e082ed  8.751751e+03
63  2025-02-20  0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb  9.666000e+03
64  2025-02-20  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  3.627100e+05
65  2025-02-20  0xb899e522b5715391ae1d4f137653e7906c5e2115  2.886146e+04
66  2025-02-20  0xbaaaf6571ab7d571043ff1e313a9609a10637864  8.177625e+05
67  2025-02-20  0xbd5fead7180a9c139fa51a103cb6a2ce86ddb5c3  2.086133e+05
68  2025-02-20  0xbee1707d6b44d4d52bfe19e41f8a828645437aab  7.213834e+04
69  2025-06-15  0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd  1.243854e+03
70  2025-06-15  0x28736f43f1e871e6aa8b1148d38d4994275d72c4  1.692362e+01
71  2025-06-15  0x47add9a56df66b524d5e2c1993a43cde53b6ed85  3.738530e+01
72  2025-06-15  0x4f93fead39b70a1824f981a54d4e55b278e9f760  1.220747e+03
73  2025-06-15  0x513b8629fe877bb581bf244e326a047b249c4ff1  6.054430e+04
75  2025-06-15  0xa0feb3725a9335f49874d7cd8eaad6be45b27416  1.449529e+03
76  2025-06-15  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  1.024602e+05
77  2025-06-15  0xbaaaf6571ab7d571043ff1e313a9609a10637864  1.860320e+00
79  2025-06-15  0xbee1707d6b44d4d52bfe19e41f8a828645437aab  1.364023e+03

In [136]:
df['Win'] = df['Closed PnL'] > 0
win_rate = df['Win'].mean() * 100 
win_rate

np.float64(42.236667718523194)

In [137]:
avg_trade_size = df['Size USD'].mean()
avg_trade_size

np.float64(5842.277902808457)

In [138]:
df['Leverage'] = df['Size USD'] / df['Start Position']
lev_dist=df['Leverage'].describe()
lev_dist

C:\Users\chanc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    7.922500e+04
mean              inf
std               NaN
min     -1.045050e+10
25%     -2.939010e-02
50%      1.854478e-02
75%      7.218634e-01
max               inf
Name: Leverage, dtype: float64

In [139]:
trades_per_day = df.groupby('Date').size()
trades_per_day=trades_per_day.reset_index(name='trades')
trades_per_day

         Date  trades
0  2023-03-28       3
1  2023-11-15     713
2  2024-03-09    3044
3  2024-07-03    2684
4  2024-10-27    9595
5  2025-02-20   61956
6  2025-06-15    1230

In [140]:
df['Direction'].unique()

<StringArray>
[                 'Buy',                 'Sell',            'Open Long',
           'Close Long', 'Spot Dust Conversion',           'Open Short',
          'Close Short',         'Short > Long',         'Long > Short',
           'Settlement']
Length: 10, dtype: str

In [141]:
def classify_position(x):
    x = x.upper()
    if 'LONG' in x:
        return 'LONG'
    elif 'SHORT' in x:
        return 'SHORT'
    else:
        return 'OTHER'

df['Position'] = df['Direction'].apply(classify_position)

In [142]:
df['Position'].value_counts(normalize=True) * 100

Position
LONG     51.074787
SHORT    33.325339
OTHER    15.599874
Name: proportion, dtype: float64

In [143]:
longs = (df['Position'] == 'LONG').sum()
shorts = (df['Position'] == 'SHORT').sum()
ratio=longs/shorts
ratio

np.float64(1.532611165820771)

In [144]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 79225 entries, 0 to 79224
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Account           79225 non-null  str
 1   Coin              79225 non-null  str
 2   Execution Price   79225 non-null  float64
 3   Size Tokens       79225 non-null  float64
 4   Size USD          79225 non-null  float64
 5   Side              79225 non-null  str
 6   Timestamp IST     79225 non-null  datetime64[us]
 7   Start Position    79225 non-null  float64
 8   Direction         79225 non-null  str
 9   Closed PnL        79225 non-null  float64
 10  Transaction Hash  79225 non-null  str
 11  Order ID          79225 non-null  int64
 12  Crossed           79225 non-null  bool
 13  Fee               79225 non-null  float64
 14  Trade ID          79225 non-null  float64
 15  Timestamp         79225 non-null  datetime64[ms, Asia/Kolkata]
 16  Date              79225 non-null  object
 17  Win               79225 non-null  bool
 18  Leverage          79225 non-null  float64
 19  Position          79225 non-null  str
dtypes: bool(2), datetime64[ms, Asia/Kolkata](1), datetime64[us](1), float64(8), int64(1), object(1), str(6)
memory usage: 11.0+ MB

In [145]:
#Second dataset
df2=pd.read_csv("C:/Users/chanc/OneDrive/Desktop/fear_greed_index.csv")
print(df2.info())
print(df2)

<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   str
 3   date            2644 non-null   str
dtypes: int64(2), str(2)
memory usage: 82.8 KB
None
       timestamp  value classification       date
0     1517463000     30           Fear   2/1/2018
1     1517549400     15   Extreme Fear   2/2/2018
2     1517635800     40           Fear   2/3/2018
3     1517722200     24   Extreme Fear   2/4/2018
4     1517808600     11   Extreme Fear   2/5/2018
...          ...    ...            ...        ...
2639  1745818200     54        Neutral  4/28/2025
2640  1745904600     60          Greed  4/29/2025
2641  1745991000     56          Greed  4/30/2025
2642  1746077400     53        Neutral   5/1/2025
2643  1746163800     67          Greed   5/2/2025

[2644 rows x 4 columns]

In [146]:
print(df2.isna().sum())
print(df2.duplicated().sum())

timestamp         0
value             0
classification    0
date              0
dtype: int64
0

In [147]:
df2['date'] = pd.to_datetime(df2['date'], dayfirst=False)
df2['date']

0      2018-02-01
1      2018-02-02
2      2018-02-03
3      2018-02-04
4      2018-02-05
          ...
2639   2025-04-28
2640   2025-04-29
2641   2025-04-30
2642   2025-05-01
2643   2025-05-02
Name: date, Length: 2644, dtype: datetime64[us]

In [148]:
df2['classification'] = df2['classification'].str.strip().str.title()
df2['classification']

0               Fear
1       Extreme Fear
2               Fear
3       Extreme Fear
4       Extreme Fear
            ...
2639         Neutral
2640           Greed
2641           Greed
2642         Neutral
2643           Greed
Name: classification, Length: 2644, dtype: str

In [149]:
df2['timestamp'] = pd.to_datetime(df2['timestamp'], unit='s')
df2['Date'] = df2['timestamp'].dt.date
df2['Date']

0       2018-02-01
1       2018-02-02
2       2018-02-03
3       2018-02-04
4       2018-02-05
           ...
2639    2025-04-28
2640    2025-04-29
2641    2025-04-30
2642    2025-05-01
2643    2025-05-02
Name: Date, Length: 2644, dtype: object

In [150]:
df2[['date','Date']].head() #To check if the date is proper or not

        date        Date
0 2018-02-01  2018-02-01
1 2018-02-02  2018-02-02
2 2018-02-03  2018-02-03
3 2018-02-04  2018-02-04
4 2018-02-05  2018-02-05

In [151]:
df2['date'].duplicated().sum()

np.int64(0)

In [152]:
df = df.merge(df2, on='Date', how='left')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 79225 entries, 0 to 79224
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Account           79225 non-null  str
 1   Coin              79225 non-null  str
 2   Execution Price   79225 non-null  float64
 3   Size Tokens       79225 non-null  float64
 4   Size USD          79225 non-null  float64
 5   Side              79225 non-null  str
 6   Timestamp IST     79225 non-null  datetime64[us]
 7   Start Position    79225 non-null  float64
 8   Direction         79225 non-null  str
 9   Closed PnL        79225 non-null  float64
 10  Transaction Hash  79225 non-null  str
 11  Order ID          79225 non-null  int64
 12  Crossed           79225 non-null  bool
 13  Fee               79225 non-null  float64
 14  Trade ID          79225 non-null  float64
 15  Timestamp         79225 non-null  datetime64[ms, Asia/Kolkata]
 16  Date              79225 non-null  object
 17  Win               79225 non-null  bool
 18  Leverage          79225 non-null  float64
 19  Position          79225 non-null  str
 20  timestamp         77995 non-null  datetime64[s]
 21  value             77995 non-null  float64
 22  classification    77995 non-null  str
 23  date              77995 non-null  datetime64[us]
dtypes: bool(2), datetime64[ms, Asia/Kolkata](1), datetime64[s](1), datetime64[us](2), float64(9), int64(1), object(1), str(7)
memory usage: 13.4+ MB

In [153]:
df[['Date', 'Closed PnL', 'value', 'classification']].head()

         Date  Closed PnL  value classification
0  2024-10-27         0.0   74.0          Greed
1  2024-10-27         0.0   74.0          Greed
2  2024-10-27         0.0   74.0          Greed
3  2024-10-27         0.0   74.0          Greed
4  2024-10-27         0.0   74.0          Greed

In [154]:
df[df['Closed PnL'] == 0].head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,...,Trade ID,Timestamp,Date,Win,Leverage,Position,timestamp,value,classification,date
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,...,8.950000e+14,2024-10-27 09:03:20+05:30,2024-10-27,False,inf,OTHER,2024-10-27 05:30:00,74.0,Greed,2024-10-27
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,...,4.430000e+14,2024-10-27 09:03:20+05:30,2024-10-27,False,0.129424,OTHER,2024-10-27 05:30:00,74.0,Greed,2024-10-27
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,...,6.600000e+14,2024-10-27 09:03:20+05:30,2024-10-27,False,1.147739,OTHER,2024-10-27 05:30:00,74.0,Greed,2024-10-27
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,...,1.080000e+15,2024-10-27 09:03:20+05:30,2024-10-27,False,0.996059,OTHER,2024-10-27 05:30:00,74.0,Greed,2024-10-27
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,...,1.050000e+15,2024-10-27 09:03:20+05:30,2024-10-27,False,0.054091,OTHER,2024-10-27 05:30:00,74.0,Greed,2024-10-27

In [155]:
df = df[df['Closed PnL'] != 0]

In [156]:
df.shape

(39259, 24)

In [157]:
df['Closed PnL'].describe()

count     39259.000000
mean        144.653838
std        1763.624463
min     -117990.104100
25%           0.785376
50%           9.331344
75%          51.751660
max      135329.090100
Name: Closed PnL, dtype: float64

In [158]:
df['classification'].value_counts()

classification
Neutral          30923
Greed             5741
Extreme Greed     1921
Name: count, dtype: int64

In [159]:
def map_regime(x):
    x = str(x).strip().lower()
    
    if 'fear' in x:
        return 'Fear'
    elif 'greed' in x:
        return 'Greed'
    else:
        return 'Neutral'
    
df['Regime'] = df['classification'].apply(map_regime)
df['Regime'].value_counts()

Regime
Neutral    31597
Greed       7662
Name: count, dtype: int64

In [160]:
df.groupby('Regime')['Closed PnL'].mean()

Regime
Greed      206.848313
Neutral    129.572214
Name: Closed PnL, dtype: float64

In [161]:
df.groupby('Regime')['Win'].mean() * 100

Regime
Greed      85.669538
Neutral    85.128335
Name: Win, dtype: float64

In [162]:
df.groupby('Regime').size()

Regime
Greed       7662
Neutral    31597
dtype: int64

In [163]:
df.groupby('Regime')['Leverage'].mean()

Regime
Greed      3195.823933
Neutral     459.303486
Name: Leverage, dtype: float64

In [164]:
df.groupby('Regime')['Size USD'].mean()

Regime
Greed      3653.529736
Neutral    6461.109602
Name: Size USD, dtype: float64

In [165]:
df2['classification']

0               Fear
1       Extreme Fear
2               Fear
3       Extreme Fear
4       Extreme Fear
            ...
2639         Neutral
2640           Greed
2641           Greed
2642         Neutral
2643           Greed
Name: classification, Length: 2644, dtype: str

In [166]:
df2['classification'].value_counts()

classification
Fear             781
Greed            633
Extreme Fear     508
Neutral          396
Extreme Greed    326
Name: count, dtype: int64

In [167]:
df['classification'].value_counts(dropna=False)

classification
Neutral          30923
Greed             5741
Extreme Greed     1921
NaN                674
Name: count, dtype: int64

In [168]:
df.info()

<class 'pandas.DataFrame'>
Index: 39259 entries, 44 to 79213
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Account           39259 non-null  str
 1   Coin              39259 non-null  str
 2   Execution Price   39259 non-null  float64
 3   Size Tokens       39259 non-null  float64
 4   Size USD          39259 non-null  float64
 5   Side              39259 non-null  str
 6   Timestamp IST     39259 non-null  datetime64[us]
 7   Start Position    39259 non-null  float64
 8   Direction         39259 non-null  str
 9   Closed PnL        39259 non-null  float64
 10  Transaction Hash  39259 non-null  str
 11  Order ID          39259 non-null  int64
 12  Crossed           39259 non-null  bool
 13  Fee               39259 non-null  float64
 14  Trade ID          39259 non-null  float64
 15  Timestamp         39259 non-null  datetime64[ms, Asia/Kolkata]
 16  Date              39259 non-null  object
 17  Win               39259 non-null  bool
 18  Leverage          39259 non-null  float64
 19  Position          39259 non-null  str
 20  timestamp         38585 non-null  datetime64[s]
 21  value             38585 non-null  float64
 22  classification    38585 non-null  str
 23  date              38585 non-null  datetime64[us]
 24  Regime            39259 non-null  str
dtypes: bool(2), datetime64[ms, Asia/Kolkata](1), datetime64[s](1), datetime64[us](2), float64(9), int64(1), object(1), str(8)
memory usage: 7.3+ MB

In [169]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   datetime64[s]
 1   value           2644 non-null   int64
 2   classification  2644 non-null   str
 3   date            2644 non-null   datetime64[us]
 4   Date            2644 non-null   object
dtypes: datetime64[s](1), datetime64[us](1), int64(1), object(1), str(1)
memory usage: 103.4+ KB

In [170]:
df2.head()

            timestamp  value classification       date        Date
0 2018-02-01 05:30:00     30           Fear 2018-02-01  2018-02-01
1 2018-02-02 05:30:00     15   Extreme Fear 2018-02-02  2018-02-02
2 2018-02-03 05:30:00     40           Fear 2018-02-03  2018-02-03
3 2018-02-04 05:30:00     24   Extreme Fear 2018-02-04  2018-02-04
4 2018-02-05 05:30:00     11   Extreme Fear 2018-02-05  2018-02-05